config/routes.rb
Rails.application.routes.draw do
  resources :firearms
  resources :barrels
  resources :outings


  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/barrel.rb
class Barrel < ApplicationRecord
  belongs_to :firearm

  def firearms_attributes=(firearm_attributes)
    firearm_attributes.values.each do |firearm_attribute|
      firearm = Firearm.new(firearm_attribute)
      self.firearms << firearm
    end
  end
end

app/models/barrel_outing.rb
class BarrelOuting < ApplicationRecord
belongs_to :barrel
belongs_to :outing
end

app/models/barrels_firearms.rb
class BarrelsFirearms < ApplicationRecord
  belongs_to :barrel
  belongs_to :firearm
end

app/models/firearm.rb
class Firearm < ApplicationRecord
  belongs_to :user
  has_many :barrels
  has_many :outings

  def barrels_attributes=(barrel_attributes)
    barrel_attributes.values.each do |barrel_attribute|
      barrel = Barrel.new(barrel_attribute)
      self.barrels << barrel
    end
  end

end

app/models/firearm_outing.rb
class FirearmOuting < ActiveRecord
  belongs_to :firearm
  belongs_to :outing
end

app/models/outing.rb
class Outing < ApplicationRecord
  belongs_to :firearm
  belongs_to :user


  def self.comp_match
    Outing.where(outing_type: "Match - Competition").last.firearm.name
  end

  def self.hunting
    Outing.where(outing_type: "Hunting").last.firearm.name
  end

  def self.range
    Outing.where(outing_type: "Range").last.firearm.name
  end
end

app/models/user.rb
# User object controller
class User < ApplicationRecord
  has_many :firearms
  has_many :outings
  has_many :barrels, through: :firearms

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :trackable,
    :validatable,
    :omniauthable, omniauth_providers: [:facebook]

  validates :name, presence: true

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def first_name
    name.split.first
  end

  def last_name
    name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include DeviseWhitelist
end

app/controllers/barrels_controller.rb
# Controller for Barrels
class BarrelsController < ApplicationController
  before_action :set_barrel, only: %i[show edit index update destroy]
  before_action :authenticate_user!

  def index
    @barrels = current_user.barrels.all
  end

  def show
    @barrel = Barrel.find_by(id: params[:id])
  end

  def new
    @barrel = current_user.barrels.build
  end

  def create
    @barrel = current_user.barrels.build(barrel_params)
    if @barrel.save
      redirect_to @barrel, notice: 'Barrel was added'
    else
      render :new
    end
  end

  def update
    if @barrel.update(barrel_params)
      redirect_to @barrel, notice: 'Barrel has been updated'
    else
      render :edit
    end
  end

  def destroy
    @barrel.destroy
    redirect_to barrels_path, notice: 'Your barrel was deleted'
  end

  private

  def set_barrel
    @barrel = Barrel.find_by(id: params[:id])
  end

  def barrel_params
    params.require(:barrel).permit(:caliber, :barrel_type, :length, :twist, :contour, :rifling, :firearm_id, firearms_attributes: [:name, :firearm_type, :description])
  end
end

app/controllers/concerns/devise_whitelist.rb
# Whitelist additional fields for devise User objects.
module DeviseWhitelist
    extend ActiveSupport::Concern
  
    included do
      # Required to accept fields created outside of devise for profiles.
      before_action :configure_permitted_parameters, if: :devise_controller?
    end
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
      update_attrs = [:password, :password_confirmation, :current_password]
      devise_parameter_sanitizer.permit :account_update, keys: update_attrs
    end
  end

app/controllers/firearms_controller.rb
class FirearmsController < ApplicationController
  before_action :set_firearm, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @firearms = current_user.firearms.includes(:barrels, :outings).all
  end

  def show
    @firearm = Firearm.find_by(id: params[:id])
  end

  def new
    @firearm = current_user.firearms.build
    @firearm.barrels.build
    @firearm.outings.build
  end

  def edit; end

  def create
    @firearm = current_user.firearms.build(firearm_params)
    if @firearm.save
      redirect_to @firearm, notice: 'Your new firearm was created'
    else
      render :new
    end
  end

  def update
    if @firearm.update(firearm_params)
      redirect_to @firearm, notice: 'Firearm was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @firearm.destroy
    redirect_to firearms_path, notice: 'Firearm was successfully destroy. A democrate loves you.'
  end

  private

  def set_firearm
    @firearm = Firearm.find_by(id: params[:id])
  end

  def firearm_params
    params.require(:firearm).permit(:name, :firearm_type, :description, :user_id, barrels_attributes: [:caliber, :barrel_type, :length, :twist, :contour, :rifling])
  end
end


# For later, outings_attributes: [:shots_fired]

app/controllers/outings_controller.rb
class OutingsController < ApplicationController
  before_action :set_outing, only: %i[show edit new index update destroy]
  before_action :authenticate_user!

  def index
    @outings = current_user.outings.includes(@firearms).all
  end

  def show
    @outing = Outing.find_by(id: params[:id])
  end

  def new
    @outing = current_user.outings.build
  end

  def create
    @outing = current_user.outings.build(outing_params)
    if @outing.save
      redirect_to @outing, notice: 'Your outing was created'
    else
      render :new
    end
  end

  def update
    if @outing.update(outing_params)
      redirect_to @outing, notice: 'Your outing has been updated'
    else
      render :edit
    end
  end

  def destroy
    @outing.destroy
    redirect_to outings_path, notice: 'The outing has been deleted'
  end

  private

  def set_outing
    @outing = Outing.find_by(id: params[:id])
  end

  def outing_params
    params.require(:outing).permit(:date, :outing_type, :shots_fired, :user_id, :firearm_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barrels_helper.rb
module BarrelsHelper
end

app/helpers/firearms_helper.rb
module FirearmsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/barrels/_edit_barrel.html.erb
<!-- <h1>Edit Barrel</h1> -->
<%= form_for(@barrel) do |f| %>
  <% if barrel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(barrel.errors.count, "error") %> prohibited this barrel from being saved:</h2>

      <ul>
      <% barrel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h5><%= f.label :caliber %></h5>
    <%= f.text_field :caliber, id: :barrel_caliber %>

  <h5><%= f.label :barrel_type %></h5>
    <%= f.text_field :barrel_type, id: :barrel_barrel_type %>

  <h5><%= f.label :length %></h5>
    <%= f.number_field :length, id: :barrel_length, :step => 0.0001 %>

    <h5><%= f.label :twist %></h5>
    <%= f.number_field :twist, id: :barrel_twist, :step => 0.0001 %>

  <h5><%= f.label :contour %></h5>
    <%= f.text_field :contour, id: :barrel_contour %>

  <h5><%= f.label :rifling %></h5>
    <%= f.text_field :rifling, id: :barrel_rifling %>
  <h5><%= f.label "Select firearm" %></h5>
    <%= f.collection_select :firearm_id, current_user.firearms, :id, :name, include_blank: "Select firearm" %>
<br><br>
   <%= f.submit 'Edit Barrel', class: "btn btn-primary" %>
  <% end %>

app/views/barrels/_new_barrel.html.erb
<h1>Create Barrel</h1>
<%= form_for([@user, @barrel]) do |f| %>
  <% if barrel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(barrel.errors.count, "error") %> prohibited this barrel from being saved:</h2>
      <ul>
      <% barrel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h5><%= f.label :caliber %></h5>
    <%= f.text_field :caliber, id: :barrel_caliber %>

  <h5><%= f.label :barrel_type %></h5>
    <%= f.text_field :barrel_type, id: :barrel_barrel_type %>

  <h5><%= f.label :length %></h5>
    <%= f.number_field :length, id: :barrel_length, :step => 0.0001 %>

    <h5><%= f.label :twist %></h5>
    <%= f.number_field :twist, id: :barrel_twist, :step => 0.0001 %>

  <h5><%= f.label :contour %></h5>
    <%= f.text_field :contour, id: :barrel_contour %>

  <h5><%= f.label :rifling %></h5>
    <%= f.text_field :rifling, id: :barrel_rifling %>

  <h5><%= f.label "Select firearm" %></h5>
    <%= f.collection_select :firearm_id, current_user.firearms, :id, :name, include_blank: "Select firearm" %>
<br><br>
   <%= f.submit 'Create Barrel', class: "btn btn-primary" %>
  <% end %>

app/views/barrels/edit.html.erb
<h1>Edit Barrel</h1>

<%= render 'edit_barrel', barrel: @barrel %>

<%= link_to 'Back', barrels_path, class: "btn btn-secondary" %>

app/views/barrels/index.html.erb
<h1><%= current_user.first_name %>'s Barrels</h1>
<div class="d-md-flex flex-md-wrap">
  <div class="card-group">
    <% @barrels.each do |b| %>
    <div class="p-3">
      <div class="card mb-3" style="min-width: 18rem;">
        <div class="card-body">
          <h2>Caliber:</h2>
          <span class="align-text-middle"><%= b.caliber %></span>
          <h4>Type:</h4>
          <span class="align-text-middle"><%= b.barrel_type %></span>
          <h4>Length:</h4>
          <span class="align-text-middle"><%= b.length %>"</span>
          <% if b.twist == nil %>
          <h4>Twist:</h4>
          <span class="align-text-middle">N/A</span>
          <% else %>
          <h4>Twist:</h4>
          <span class="align-text-middle">1:<%= b.twist %></span>
          <% end %>
          <h4>Contour:</h4>
          <span class="align-text-middle"><%= b.contour %></span>
          <h4>Rifling:</h4>
          <span class="align-text-middle"><%= b.rifling %></span>
          <h5>Firearm:</h5>
          <%= link_to b.firearm.name, firearm_path(b.firearm.id) %>
          <br><br>
          <%= link_to 'Show', barrel_path(b), class: "card-link btn btn-primary" %>
          <%= link_to 'Edit', edit_barrel_path(b), class: "card-link btn btn-warning" %>
        <%= link_to 'Destroy', barrel_path(b), method: :delete, data: { confirm: 'Are you sure?' }, class: "card-link btn btn-danger" %></div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<br><br>
<div class="d-flex justify-content-around">
  <%= link_to 'New Barrel', new_barrel_path, class: "btn btn-outline-success" %>
</div>

app/views/barrels/new.html.erb
<!-- New Barrel -->
<%= render 'new_barrel', barrel: @barrel %>

<%= link_to 'Back', barrels_path, class: "btn btn-secondary" %>

app/views/barrels/show.html.erb
<h1><%= current_user.first_name %>'s Barrels</h1>
<div class="d-md-flex flex-md-wrap">
  <div class="card-group">
    <div class="p-3"><div class="card mb-3" style="min-width: 18rem;">
      <div class="card-body">
        <h5>Caliber:</h5>
          <%= @barrel.caliber %>
          <h5>Type:</h5>
          <%= @barrel.barrel_type %>
          <h5>Length:</h5>
          <%= @barrel.length %>"
          <% if @barrel.twist == nil %>
          <h4>Twist:</h4>
          N/A
          <% else %>
          <h4>Twist:</h4>
          1:<%= @barrel.twist %>
          <% end %>
          <h5>Contour:</h5>
          <%= @barrel.contour %>
          <h5>Rifling:</h5>
          <%= @barrel.rifling %>
          <h5>Firearm:</h5>
          <%= link_to @barrel.firearm.name, firearm_path(@barrel.firearm.id) %>
          <br><br>
          <%= link_to 'Back', barrels_path, class: "card-link btn btn-primary" %>
          <%= link_to 'Edit', edit_barrel_path(@barrel), class: "card-link btn btn-warning" %>
        <%= link_to 'Destroy', barrel_path(@barrel), method: :delete, data: { confirm: 'Are you sure?' }, class: "card-link btn btn-danger" %></div>
      </div>
    </div>
  </div>
</div>

app/views/firearms/_new_firearm.html.erb
<%= form_for([@user, @firearm]) do |f| %>
  <h5><%= f.label :name, "Name" %></h5>
    <%= f.text_field :name %> <br>
  <h5><%= f.label :firearm_type, "Type" %></h5>
  <%= f.select :firearm_type, options_for_select(["Bolt-Action","Semi-Auto","Muzzle Loader","Shotgun",], @firearm.firearm_type), selected: true %>
  <h5><%= f.label :description,   "Description" %></h5>
    <%= f.text_area :description %> <br>

    <!-- Add new barrel -->
    <h3>Add new barrel</h3>
  <%= f.fields_for :barrels do |bf| %>
    <h5><%= bf.label :caliber %></h5>
      <%= bf.text_field :caliber %>
    <h5><%= bf.label :barrel_type %></h5>
      <%= bf.text_field :barrel_type %>
    <h5><%= bf.label :length %></h5>
      <%= bf.number_field :length, id: :barrel_length, :step => 0.0001 %>
    <h5><%= bf.label :twist %></h5>
      <%= bf.number_field :twist, id: :barrel_twist, :step => 0.0001 %>
    <h5><%= bf.label :contour %></h5>
      <%= bf.text_field :contour %>
    <h5><%= bf.label :rifling %></h5>
      <%= bf.text_field :rifling %>
      <% end %>
      <br><br>
<%= f.submit 'Create Firearm', class: "btn btn-primary" %>
<% end %>

app/views/firearms/edit.html.erb
<h2>Edit a firearm</h2>
<%= form_for(@firearm) do |f| %>
    <h5><%= f.label :name, "Name" %></h5><%= f.text_field :name %> <br>
    <h5><%= f.label :firearm_type, "Type" %></h5><%= f.text_field :firearm_type %> <br>
    <h5><%= f.label :description, "Description" %></h5><%= f.text_area :description %> <br>
    <%= f.submit 'Update Firearm', class: "btn btn-primary" %>
<% end %>
<%= link_to  "Back", firearms_path, class: "btn btn-outline-secondary" %>

app/views/firearms/index.html.erb
<div class="d-md-flex flex-md-wrap">
    <div class="card-group">
        <% @firearms.each do |f| %>
        <div class="p-5">
            <div class="card mb-3" style="min-width: 18rem;">
                <div class="card-body">
                    <h2>
                    <%= f.name %>
                    </h2>
                    <h4>Type of firearm:</h4>
                    <%= f.firearm_type %>
                    <h4>Description</h4>
                    <%= f.description %>
                    <h5>Current barrel:</h5>
                    <%= link_to f.barrels.last.caliber, barrel_path(f.barrels.last.id) %>
                    <br><br>
                    <%= link_to  "Show", firearm_path(f), class: "btn btn-outline-success" %>
                    <%= link_to  "Edit", edit_firearm_path(f), class: "btn btn-outline-warning" %>
                    <%= link_to 'Destroy', firearm_path(f), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>
<br>
<br>
<div class="d-flex justify-content-around">
    <%= link_to 'New Firearm', new_firearm_path, class: "btn btn-outline-success" %>
</div>

app/views/firearms/new.html.erb
<h2>Add a new firearm</h2>
<%= render 'new_firearm', firearm: @firearm %>

<%= link_to  "Back", firearms_path, class: "btn btn-outline-secondary" %>

app/views/firearms/show.html.erb
<div class="d-md-flex flex-md-wrap">
    <div class="card-group">
        <div class="p-5">
            <div class="card mb-3" style="min-width: 18rem;">
                <div class="card-body">
                    <h1>
                    <%= @firearm.name %>
                    </h1>
                    <h4>Type</h4>
                    <%= @firearm.firearm_type %>
                    <h4>Description</h4>
                    <%= @firearm.description %>
                    <h3>Current barrel:</h3>
                    <%= link_to @firearm.barrels.last.caliber, barrel_path(@firearm.barrels.last.id)%>
                    <h5>Total shots fired from current barrel</h5>
                    <%= @firearm.outings.sum(:shots_fired) %>
                    <br><br>
                    <%= link_to  "Back", firearms_path, class: "btn btn-outline-secondary" %>
                    <%= link_to  "Edit Firearm", edit_firearm_path(@firearm), class: "btn btn-outline-warning"  %>
                    <%= link_to 'Destroy', firearm_path(@firearm), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RailsDownTheTube</title>
  <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
        <a class="navbar-brand text-white p-2" href="/"><% if user_signed_in? && current_user.image? %><%= image_tag current_user.image + "?type=small", class: "d-inline-block mr-2 rounded" %><% end %>DownTheTu.be</a>
        <button class="navbar-toggler text-white" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <div class="navbar-nav">
                <% if user_signed_in? %>
                  <%= link_to "Edit profile", edit_user_registration_path, class: 'nav-item nav-link text-white' %>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-item nav-link text-white'  %>
                  <%= link_to  "Firearms", firearms_path, class: "btn btn-outline-success" %>
                  <%= link_to  "Barrels", barrels_path, class: "btn btn-outline-success" %>
                  <%= link_to  "Outings", outings_path, class: "btn btn-outline-success" %>
                <% else %>
                  <%= link_to "Sign Up!", new_user_registration_path, class: 'nav-item nav-link text-white'  %>
                  <%= link_to "Login", new_user_session_path, class: 'nav-item nav-link text-white'  %>
                <% end %>
              </nav>
  <p class="notice">
    <%= notice %>
  </p>
  <p class="alert">
    <%= alert %>
  </p>
  <div class="container-fluid">
    <%= yield %>
  </div>
</body>

</html>

app/views/outings/_edit_outing.html.erb
<h1>Edit Outing</h1>
<%= form_for(@outing) do |f| %>
<% if outing.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(outing.errors.count, "error") %> prohibited this barrel from being saved:</h2>
  <ul>
    <% outing.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<h5>Current Date:</h5>
<%= outing.date.strftime("%B %d, %Y") %>
<h5><%= f.label "New Date if Necessary" %></h5>
<%= f.date_select('date', order: [:month, :day, :year]) %>

<h5><%= f.label "Firearm used" %></h5>
<%= f.collection_select :firearm_id, current_user.firearms, :id, :name, include_blank: "Select firearm" %>
<h5><%= f.label :shots_fired %></h5>
<%= f.text_field :shots_fired, id: :outing_shots_fired %>
<br><br>
<%= f.submit 'Edit Outing', class: "btn btn-primary" %>
<% end %>

app/views/outings/_new_outing.html.erb
<h1>New Outing</h1>
<%= form_for(@outing) do |f| %>
  <% if outing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(outing.errors.count, "error") %> prohibited this barrel from being saved:</h2>

      <ul>
      <% outing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h5><%= f.label :outing_type, "Type" %></h5>
    <%= f.select :outing_type, options_for_select(["Match - Competition","Hunting","Range",], @outing.outing_type), selected: true %>
  <h5><%= f.label :date %></h5>
    <%= f.date_select('date', order: [:month, :day, :year]) %>

  <h5><%= f.label "Select firearm" %></h5>
    <%= f.collection_select :firearm_id, current_user.firearms, :id, :name, include_blank: "Select firearm" %>
  <h5><%= f.label :shots_fired %></h5>
    <%= f.text_field :shots_fired, id: :outing_shots_fired %>

<br><br>
   <%= f.submit 'Create Outing', class: "btn btn-primary" %>
  <% end %>

app/views/outings/edit.html.erb
<!-- <h1>New Barrel</h1> -->

<%= render 'edit_outing', outing: @outing %>

<%= link_to 'Back', outings_path, class: "btn btn-secondary" %>

app/views/outings/index.html.erb
<h1><%= current_user.first_name %>'s Outings</h1>
<div class="">
  <p>Below you will see the last firearm you used for each of the outing types available.</p>

    <h2>Range</h2>
    <%= link_to Outing.range, firearm_path(Outing.where(outing_type: "Range").last.firearm.id) %>
    <h2>Hunting</h2>
    <%= link_to Outing.hunting, firearm_path(Outing.where(outing_type: "Hunting").last.firearm.id) %>
    <h2>Match - Competition</h2>
    <%= link_to Outing.comp_match, firearm_path(Outing.where(outing_type: "Match - Competition").last.firearm.id) %>
    </div>
<div class="d-md-flex flex-md-wrap">
  <div class="card-group">
    <% @outings.each do |o| %>
    <div class="p-3">
      <div class="card mb-3" style="min-width: 18rem;">
        <div class="card-body">
          <h4>Outing Type:</h4>
          <%= o.outing_type %>
          <h4>Outing Date:</h4>
          <%= o.date.strftime("%B %d, %Y") %>
          <h4>Shots Fired:</h4>
          <%= o.shots_fired %>
          <br>
          <%= link_to 'Show', outing_path(o), class: "btn btn-primary" %>
          <%= link_to 'Edit', edit_outing_path(o), class: "btn btn-warning" %>
        <%= link_to 'Destroy', outing_path(o), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></div>
      </div>
    </div>

    <% end %>
  </div>
</div>
<br><br>
<div class="d-flex justify-content-around">
  <%= link_to 'New Outing', new_outing_path, class: "btn btn-outline-success" %>
</div>

app/views/outings/new.html.erb
<!-- New Outing -->
<%= render 'new_outing', outing: @outing %>

<%= link_to 'Back', outings_path, class: "btn btn-secondary" %>

app/views/outings/show.html.erb
<h1><%= current_user.first_name %>'s Outings</h1>
  <h5>Date of outing:</h5>
    <%= @outing.date.strftime("%B %d, %Y") %>
  <h5>Outing Type:</h5>
  <%= @outing.outing_type %>
  <h5>Shots Fired:</h5>
    <%= @outing.shots_fired %>
  <h5>Firearm:</h5>
    <%= link_to @outing.firearm.name, firearm_path(@outing.firearm.id) %>
  <br><br>
<%= link_to 'Edit', edit_outing_path(@outing), class: "btn btn-outline-warning" %>
<%= link_to 'Back', outings_path, class: "btn btn-outline-secondary" %>
<%= link_to 'Destroy', outing_path(@outing), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

app/views/pages/barrel_form.html.erb
Input barrel info

Choose existing firearm or add a new one

app/views/pages/barrel_form_reference.html.erb
<%= f.fields_for :firearms %>
<h5><%= ff.label "Select firearm" %></h5>
    <%= f.collection_select :firearm_id, current_user.firearms, :id, :name, prompt: "Select firearm" %>
    <% end %>


    <h1>Create Barrel</h1>
<%= form_for([@user, @barrel]) do |f| %>
  <% if barrel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(barrel.errors.count, "error") %> prohibited this barrel from being saved:</h2>
      <ul>
      <% barrel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h5><%= f.label :caliber %></h5>
    <%= f.text_field :caliber, id: :barrel_caliber %>

  <h5><%= f.label :barrel_type %></h5>
    <%= f.text_field :barrel_type, id: :barrel_barrel_type %>

  <h5><%= f.label :length %></h5>
    <%= f.number_field :length, id: :barrel_length, :step => 0.0001 %>

    <h5><%= f.label :twist %></h5>
    <%= f.number_field :twist, id: :barrel_twist, :step => 0.0001 %>

  <h5><%= f.label :contour %></h5>
    <%= f.text_field :contour, id: :barrel_contour %>

  <h5><%= f.label :rifling %></h5>
    <%= f.text_field :rifling, id: :barrel_rifling %>
<br>


<br><br>
   <%= f.submit 'Create Barrel', class: "btn btn-primary" %>
  <% end %>

app/views/pages/firearm_form.html.erb
Input firearm info

Input barrel info

Initial shots fired count


<h5><%= f.label "Select firearm" %></h5>
    <%= f.collection_select :firearm_id, current_user.firearms, :id, :name, prompt: "Select firearm" %>

app/views/pages/index.html.erb
<h2>Welcome, <% if user_signed_in? && current_user.name %><%= current_user.first_name %><% else %> Shooter<% end %>!</h2>

app/views/pages/outing_form.html.erb
Choose Firearm

Choose Barrel

Enter Date

Record Shots Fired



<%= link_to  "Barrels", firearm_barrels_path(@firearm,@barrels), class: "btn btn-outline-success" %>
                  <%= link_to  "Outings", firearm_outings_path(@firearm, @outings), class: "btn btn-outline-success" %>